spring.application.name=stocky

spring.datasource.url=(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g46838a187910ec_dbstocky_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes))))

# CREDENCIALES DE ORACLE CLOUD
spring.datasource.username=ADMIN
spring.datasource.password=14A8agua4,.-

#EL NUEVO DRIVER
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#EL DIALECTO (NUEVO: Para que Hibernate sepa que ahora hablo con Oracle y no con MySQL)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Opcional en caso de ser necesario ocuparlo miau
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true